### ISSUE TITLE
FNG mcnp to openmc csg2csg conversion

### ISSUE THREAD

**Issue by zxkjack123** [pshriwise/dag-openmc-cmp#7]
Currently working on csg2csg converting fng mcnp input to a openmc geometry. Encounters a bug, debugging ...

**Comment by zxkjack123** [comment]
Found that it's not the bug of `csg2cs2`, it's the reason of mcnp input file format. Lines before header caused this problem. Solved.

**Comment by zxkjack123** [comment]
The FNG OpenMC `geometry.xml` and `materials.xml` could see branch `fng_comp`, `FNG/geometry/openmc`.

**Comment by zxkjack123** [comment]
The `geometry.xml` converted from mcnp input file has the following problem:
```
ERROR: No boundary conditions were applied to any surfaces!
application called MPI_Abort(MPI_COMM_WORLD, -1) - process 0
[unset]: write_line error; fd=-1 buf=:cmd=abort exitcode=-1
:
system msg for write_line failure : Bad file descriptor
Traceback (most recent call last):
  File "input.py", line 157, in <module>
    main(args.geom, args.nps, args.run, args.plot, args.vol)
  File "input.py", line 129, in main
    openmc.run()
  File "/home/zxk/opt/openmc/openmc/executor.py", line 212, in run
    _run(args, output, cwd)
  File "/home/zxk/opt/openmc/openmc/executor.py", line 30, in _run
    ''.join(lines))
subprocess.CalledProcessError: Command 'openmc' died with <Signals.SIGSEGV: 11>.
```

@pshriwise I checked the original mcnp input file, there isn't a reflecting surface. Why this error happens?

**Comment by zxkjack123** [comment]
Problem fixed by manually change the boundary type of some surfaces.
